const state = {
  mode: localStorage.getItem('clarity-mode') || 'professional',
  view: 'overview',
  case: { title:'The Missing Float', type:'Missing property', location:'Riverside Community Centre', date:'Today, 14:20', summary:'Cash from the reception float was discovered missing after the afternoon handover.' },
  people:[{name:'Alex Morgan', role:'Staff member', note:'Had key access; says they left at 14:05'},{name:'Jordan Lee', role:'Volunteer', note:'Was in the reception area during the handover'},{name:'Sam Taylor', role:'Visitor', note:'Signed in, but departure time is unclear'},{name:'Casey Wright', role:'Staff member', note:'Reported the missing cash at 14:20'}],
  evidence:[{title:'Handover sheet', kind:'Document', strength:'Strong', detail:'Signed at 14:12; amount recorded as £500.'},{title:'Front desk statement', kind:'Statement', strength:'Moderate', detail:'Witness heard the cash drawer open around 14:10.'},{title:'Entry log', kind:'Digital record', strength:'Strong', detail:'Four people had access during the relevant window.'}],
  events:[['13:55','Alex signs into reception','Entry log'],['14:05','Alex says they leave early','Statement'],['14:10','Cash drawer reportedly opened','Witness statement'],['14:12','Handover sheet signed','Document'],['14:20','Shortfall reported','Case report']],
  questions:['Who can independently confirm Alex left at 14:05?','Was the cash drawer visibly locked between 14:05 and 14:10?','Can the entry log identify who accessed reception at 14:10?'],
  hypotheses:[['Cash was misplaced during handover',42],['Unauthorised removal by someone with access',35],['Amount was recorded incorrectly',23]]
};
const esc = s => String(s).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function persist(){localStorage.setItem('clarity-mode',state.mode)}
function app(){ document.getElementById('app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">◈</span> Clarity</div><div><div class="side-label">Workspace</div><nav class="nav">${nav('overview','Overview','▦')}${nav('case','Case file','▣')}${nav('timeline','Timeline','◷')}${nav('evidence','Evidence','◇')}${nav('questions','Questions','?')}${nav('report','Case report','≡')}</nav></div><div class="mode-card"><strong>${state.mode==='kids'?'Kids mode':'Professional mode'}</strong><span>${state.mode==='kids'?'Friendly, fair and simple dispute resolution.':'Evidence-first decision support. No guilt scores.'}</span><div class="switch">Switch mode <button aria-label="Switch mode" class="toggle ${state.mode==='kids'?'on':''}" onclick="toggleMode()"><i></i></button></div></div></aside><main><header class="topbar"><div class="breadcrumb">Workspace / ${state.view[0].toUpperCase()+state.view.slice(1)}</div><div class="top-actions"><button class="btn ghost" onclick="newCase()">＋ New case</button><span class="avatar">JM</span></div></header><section class="content">${renderView()}</section></main></div>`; }
function nav(id,label,icon){return `<button class="${state.view===id?'active':''}" onclick="go('${id}')">${icon}&nbsp; ${label}</button>`}
function go(v){state.view=v;app()}
function toggleMode(){state.mode=state.mode==='kids'?'professional':'kids';persist();app()}
function renderView(){ if(state.view==='case')return caseView(); if(state.view==='timeline')return timelineView(); if(state.view==='evidence')return evidenceView(); if(state.view==='questions')return questionsView(); if(state.view==='report')return reportView(); return overview(); }
function heading(kicker,title,sub){return `<div class="small muted">${kicker.toUpperCase()}</div><h1>${title}</h1><p class="subtitle">${sub}</p>`}
function overview(){const kid=state.mode==='kids';return heading(kid?'KIDS MODE • FAIR PLAY DESK':'CASE OVERVIEW',kid?'Let’s work out what happened':'Good afternoon, Jack',kid?'Everyone gets a chance to explain. We look for facts, feelings and a fair next step.':`Active case: ${esc(state.case.title)} • Last updated just now.`)+`${kid?'<div class="notice kids">🌈 <span><b>Fair-play promise:</b> We do not call anyone a liar or a thief. We listen to everyone and look for a safe, fair solution.</span></div>':'<div class="notice">ⓘ <span><b>Decision-support only:</b> Clarity organises information and surfaces unanswered questions. It does not identify culprits or make accusations.</span></div>'}<div class="grid three"><div class="card stat"><div><div class="number">${state.evidence.length}</div><div class="label">Evidence items</div></div><span class="pill blue">Tracked</span></div><div class="card stat"><div><div class="number">${state.people.length}</div><div class="label">People recorded</div></div><span class="pill">Neutral</span></div><div class="card stat"><div><div class="number">${state.questions.length}</div><div class="label">Open questions</div></div><span class="pill amber">To review</span></div></div><div class="grid two" style="margin-top:18px"><div class="card"><div class="card-head"><div><h2>${kid?'What we know so far':'Evidence-led picture'}</h2><p class="muted small">${kid?'Facts everyone agrees on':'Alternative explanations, not suspect rankings'}</p></div><button class="btn ghost" onclick="go('report')">View report →</button></div>${state.hypotheses.map(h=>`<div class="meter-row"><label>${esc(h[0])}</label><div class="meter"><span style="width:${h[1]}%"></span></div><b>${h[1]}%</b></div>`).join('')}<div class="footer-note">ⓘ These are review weights, not probabilities of guilt.</div></div><div class="card"><div class="card-head"><div><h2>${kid?'People’s stories':'Next best questions'}</h2><p class="muted small">Resolve uncertainty before conclusions</p></div><button class="btn ghost" onclick="go('questions')">See all</button></div>${state.questions.slice(0,3).map((q,i)=>`<div class="question"><p>${esc(q)}</p><span class="pill amber">Open</span></div>`).join('')}</div></div><div class="card" style="margin-top:18px"><div class="card-head"><div><h2>Recent activity</h2><p class="muted small">An auditable record of the case</p></div><button class="btn ghost" onclick="go('timeline')">Open timeline</button></div>${state.events.slice(-3).reverse().map(e=>`<div class="list-item"><div><strong>${esc(e[1])}</strong><p>${esc(e[2])}</p></div><span class="small muted">${esc(e[0])}</span></div>`).join('')}</div>`}
function caseView(){return heading('CASE FILE','Case details','Keep observations, assumptions and decisions clearly separated.')+`<div class="card"><form onsubmit="saveCase(event)"><div class="form-grid"><div class="field"><label>Case name</label><input name="title" value="${esc(state.case.title)}" required></div><div class="field"><label>Incident type</label><input name="type" value="${esc(state.case.type)}"></div><div class="field"><label>Location</label><input name="location" value="${esc(state.case.location)}"></div><div class="field"><label>Date and time</label><input name="date" value="${esc(state.case.date)}"></div><div class="field full"><label>Neutral incident summary</label><textarea name="summary">${esc(state.case.summary)}</textarea></div></div><div class="form-actions"><button type="button" class="btn light" onclick="go('overview')">Cancel</button><button class="btn">Save case</button></div></form></div><div class="grid two" style="margin-top:18px"><div class="card"><div class="card-head"><h2>People involved</h2><button class="btn ghost" onclick="addPerson()">＋ Add person</button></div>${peopleHtml()}</div><div class="card"><h2>Case guardrails</h2><p class="muted">This workspace records information without labelling anyone guilty. Use authorised procedures for safeguarding, emergency response and formal investigations.</p><span class="pill">Human review required</span></div></div>`}
function peopleHtml(){return `<div class="list">${state.people.map((p,i)=>`<div class="list-item"><div><strong>${esc(p.name)}</strong><p>${esc(p.role)} · ${esc(p.note)}</p></div><button class="btn danger" onclick="removePerson(${i})">Remove</button></div>`).join('')}</div>`}
function timelineView(){return heading('TIMELINE','What happened, and when?','Separate recorded events from estimates. Unknown times are allowed.')+`<div class="grid two"><div class="card"><div class="card-head"><div><h2>Case timeline</h2><p class="muted small">${state.events.length} events • newest additions are saved locally</p></div><button class="btn ghost" onclick="addEvent()">＋ Add event</button></div><div class="timeline">${state.events.map(e=>`<div class="event"><time>${esc(e[0])}</time><span class="dot"></span><div><strong>${esc(e[1])}</strong><p>${esc(e[2])}</p></div></div>`).join('')}</div></div><div class="card"><h2>Timeline checks</h2><div class="question"><p>Are any events based on memory rather than a record?</p><span class="pill amber">Review</span></div><div class="question"><p>Is there an unexplained access window?</p><span class="pill amber">Review</span></div><div class="question"><p>Have conflicting accounts been preserved verbatim?</p><span class="pill blue">Required</span></div></div></div>`}
function evidenceView(){return heading('EVIDENCE','Evidence register','Record what was observed, where it came from and how strong the source is—not what it proves by itself.')+`<div class="card"><div class="card-head"><div><h2>Evidence items</h2><p class="muted small">${state.evidence.length} items in this case</p></div><button class="btn" onclick="addEvidence()">＋ Add evidence</button></div><div class="list">${state.evidence.map((e,i)=>`<div class="list-item"><div><strong>${esc(e.title)}</strong><p>${esc(e.kind)} · ${esc(e.detail)}</p></div><span class="pill ${e.strength==='Strong'?'blue':'amber'}">${esc(e.strength)}</span></div>`).join('')}</div></div>`}
function questionsView(){return heading('QUESTIONS','Questions to resolve','Neutral prompts generated from gaps and contradictions. Record answers with their source.')+`<div class="grid two"><div class="card"><div class="card-head"><h2>Open questions</h2><button class="btn" onclick="addQuestion()">＋ Add question</button></div>${state.questions.map((q,i)=>`<div class="question"><p>${esc(q)}</p><button class="btn light small" onclick="answerQuestion(${i})">Mark answered</button></div>`).join('')}</div><div class="card"><h2>Question principles</h2><div class="list-item"><div><strong>Ask for observations</strong><p>“What did you see or hear?” rather than “Did you take it?”</p></div></div><div class="list-item"><div><strong>Preserve uncertainty</strong><p>Record “I don’t know” as a valid answer.</p></div></div><div class="list-item"><div><strong>Keep it age-appropriate</strong><p>${state.mode==='kids'?'Use short, gentle questions and involve a trusted adult.':'For children, use Kids mode and follow safeguarding procedures.'}</p></div></div></div></div>`}
function reportView(){return heading('CASE REPORT','Review before you act','A neutral, exportable summary. It deliberately avoids naming a culprit.')+`<div class="notice">ⓘ <span>Only authorised people should share this report. Verify every fact against original records before relying on it.</span></div><div class="card" id="report"><h2>${esc(state.case.title)}</h2><p class="muted">${esc(state.case.type)} · ${esc(state.case.location)} · ${esc(state.case.date)}</p><hr><h3>Incident summary</h3><p>${esc(state.case.summary)}</p><h3>Known people</h3><p>${state.people.map(p=>`<b>${esc(p.name)}</b> (${esc(p.role)})`).join(' · ')}</p><h3>Alternative explanations to test</h3><ol>${state.hypotheses.map(h=>`<li>${esc(h[0])} — review weight ${h[1]}%</li>`).join('')}</ol><h3>Unresolved questions</h3><ul>${state.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ul><div class="form-actions"><button class="btn" onclick="window.print()">Print / save PDF</button></div></div>`}
function saveCase(e){e.preventDefault();const f=new FormData(e.target);Object.assign(state.case,Object.fromEntries(f));go('overview')}
function newCase(){if(!confirm('Start a new case? The current case stays in this browser until replaced.'))return;state.case={title:'Untitled case',type:'Incident',location:'',date:'Today',summary:''};state.people=[];state.evidence=[];state.events=[];state.questions=[];state.hypotheses=[['Explanation to investigate',50],['Alternative explanation',50]];go('case')}
function addPerson(){const name=prompt('Person name or neutral label:');if(!name)return;state.people.push({name,role:prompt('Role (witness, reporter, visitor, etc.):')||'Person involved',note:prompt('What is the recorded observation?')||'No observation recorded'});app()}
function removePerson(i){state.people.splice(i,1);app()}
function addEvent(){const time=prompt('Time or time range:');if(!time)return;state.events.push([time,prompt('What happened?')||'Unspecified event',prompt('Source (record, statement, observation):')||'Unverified']);app()}
function addEvidence(){const title=prompt('Evidence title:');if(!title)return;state.evidence.push({title,kind:prompt('Type (document, statement, photo, record):')||'Uncategorised',strength:prompt('Source strength (Strong, Moderate, Limited):')||'Limited',detail:prompt('Neutral description:')||'No description recorded'});app()}
function addQuestion(){const q=prompt('Write a neutral question:');if(q){state.questions.push(q);app()}}
function answerQuestion(i){state.questions.splice(i,1);app()}
app();
